[package]
name = "codecrafters-shell"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2024"
rust-version = "1.91"

[dependencies]
rustyline = { version = "17.0.2", features = ["derive"] }
rustyline-derive = "0.11.1"                             # error handling
